// src/views/Settings/dialogs/VRChatConfigDialog.vue
<template>
    <Dialog :open="isVRChatConfigDialogVisible" @update:open="(open) => (open ? null : closeDialog())">
        <DialogContent>
            <DialogHeader>
                <DialogTitle>{{ t('dialog.config_json.header') }}</DialogTitle>
            </DialogHeader>
            <div>
                <div class="text-xs break-keep">
                    {{ t('dialog.config_json.description1') }} <br />
                    {{ t('dialog.config_json.description2') }}
                </div>
                <br />
                <span class="mr-1.5">{{ t('dialog.config_json.cache_size') }}</span>
                <span v-text="VRChatUsedCacheSize"></span>
                <span>/</span>
                <span v-text="totalCacheSize"></span>
                <span>GB</span>
                <TooltipWrapper side="top" :content="t('dialog.config_json.refresh')">
                    <Button
                        class="rounded-full ml-1.5"
                        variant="outline"
                        size="icon-sm"
                        :disabled="VRChatCacheSizeLoading"
                        @click="getVRChatCacheSize">
                        <Spinner v-if="VRChatCacheSizeLoading" />
                        <RefreshCw v-else />
                    </Button>
                </TooltipWrapper>

                <div class="mt-2">
                    <span class="mr-1.5">{{ t('dialog.config_json.delete_all_cache') }}</span>
                    <Button class="ml-1.5" size="sm" variant="outline" @click="showDeleteAllVRChatCacheConfirm">{{
                        t('dialog.config_json.delete_cache')
                    }}</Button>
                </div>

                <div class="mt-2">
                    <span class="mr-1.5">{{ t('dialog.config_json.delete_old_cache') }}</span>
                    <Button class="ml-1.5" size="sm" variant="outline" @click="sweepVRChatCache">{{
                        t('dialog.config_json.sweep_cache')
                    }}</Button>
                </div>

                <div class="mt-2" v-for="(item, value) in VRChatConfigList" :key="value" style="display: block">
                    <span style="word-break: keep-all">{{ item.name }}:</span>
                    <div style="display: flex">
                        <InputGroupAction
                            class="mt-1.5"
                            v-model="VRChatConfigFile[value]"
                            :placeholder="item.default"
                            size="sm"
                            :type="item.type ? item.type : 'text'"
                            :min="item.min"
                            :max="item.max"
                            @input="refreshDialogValues"
                            style="flex: 1">
                            <template #actions>
                                <Button
                                    size="icon-sm"
                                    variant="outline"
                                    v-if="item.folderBrowser"
                                    @click="openConfigFolderBrowser(value)">
                                    <FolderOpen />
                                </Button>
                            </template>
                        </InputGroupAction>
                    </div>
                </div>

                <div style="display: inline-block; margin-top: 8px">
                    <span>{{ t('dialog.config_json.camera_resolution') }}</span>
                    <br />
                    <Select
                        :model-value="vrchatCameraResolutionKey"
                        @update:modelValue="(v) => (vrchatCameraResolutionKey = v)">
                        <SelectTrigger size="sm" style="margin-top: 6px">
                            <SelectValue :placeholder="getVRChatCameraResolution()" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectGroup>
                                <SelectItem
                                    v-for="row in VRChatCameraResolutions"
                                    :key="row.name"
                                    :value="getVRChatResolutionKey(row)">
                                    {{ row.name }}
                                </SelectItem>
                            </SelectGroup>
                        </SelectContent>
                    </Select>
                </div>
                <br />

                <div style="display: inline-block; margin-top: 8px">
                    <span>{{ t('dialog.config_json.spout_resolution') }}</span>
                    <br />
                    <Select
                        :model-value="vrchatSpoutResolutionKey"
                        @update:modelValue="(v) => (vrchatSpoutResolutionKey = v)">
                        <SelectTrigger size="sm" style="margin-top: 6px">
                            <SelectValue :placeholder="getVRChatSpoutResolution()" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectGroup>
                                <SelectItem
                                    v-for="row in VRChatScreenshotResolutions"
                                    :key="row.name"
                                    :value="getVRChatResolutionKey(row)">
                                    {{ row.name }}
                                </SelectItem>
                            </SelectGroup>
                        </SelectContent>
                    </Select>
                </div>
                <br />

                <div style="display: inline-block; margin-top: 8px">
                    <span>{{ t('dialog.config_json.screenshot_resolution') }}</span>
                    <br />
                    <Select
                        :model-value="vrchatScreenshotResolutionKey"
                        @update:modelValue="(v) => (vrchatScreenshotResolutionKey = v)">
                        <SelectTrigger size="sm" style="margin-top: 6px">
                            <SelectValue :placeholder="getVRChatScreenshotResolution()" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectGroup>
                                <SelectItem
                                    v-for="row in VRChatScreenshotResolutions"
                                    :key="row.name"
                                    :value="getVRChatResolutionKey(row)">
                                    {{ row.name }}
                                </SelectItem>
                            </SelectGroup>
                        </SelectContent>
                    </Select>
                </div>
                <br />

                <label class="inline-flex items-center gap-2" style="margin-top: 6px; display: block">
                    <Checkbox
                        v-model="VRChatConfigFile.picture_output_split_by_date"
                        @update:modelValue="refreshDialogValues" />
                    <span>{{ t('dialog.config_json.picture_sort_by_date') }}</span>
                </label>
                <label class="inline-flex items-center gap-2" style="margin-top: 6px; display: block">
                    <Checkbox v-model="VRChatConfigFile.disableRichPresence" @update:modelValue="refreshDialogValues" />
                    <span>{{ t('dialog.config_json.disable_discord_presence') }}</span>
                </label>
            </div>
            <DialogFooter>
                <div style="display: flex; align-items: center; justify-content: space-between" class="w-full">
                    <div>
                        <Button
                            variant="outline"
                            @click="openExternalLink('https://docs.vrchat.com/docs/configuration-file')"
                            >{{ t('dialog.config_json.vrchat_docs') }}</Button
                        >
                    </div>
                    <div>
                        <Button variant="secondary" class="mr-2" @click="closeDialog">{{
                            t('dialog.config_json.cancel')
                        }}</Button>
                        <Button :disabled="loading" @click="saveVRChatConfigFile">{{
                            t('dialog.config_json.save')
                        }}</Button>
                    </div>
                </div>
            </DialogFooter>
        </DialogContent>
    </Dialog>
</template>

<script setup>
    import { invoke } from '@tauri-apps/api/core';
    import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
    import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
    import { computed, ref, watch } from 'vue';
    import { FolderOpen, RefreshCw } from 'lucide-vue-next';
    import { Button } from '@/components/ui/button';
    import { Checkbox } from '@/components/ui/checkbox';
    import { InputGroupAction } from '@/components/ui/input-group';
    import { Spinner } from '@/components/ui/spinner';
    import { storeToRefs } from 'pinia';
    import { toast } from 'vue-sonner';
    import { useI18n } from 'vue-i18n';

    import { useAdvancedSettingsStore, useGameStore, useModalStore } from '../../../stores';
    import { runSweepVRChatCacheFlow as sweepVRChatCache } from '../../../coordinators/gameCoordinator';
    import { VRChatCameraResolutions, VRChatScreenshotResolutions } from '../../../shared/constants';
    import { getVRChatResolution, openExternalLink } from '../../../shared/utils';

    const { VRChatUsedCacheSize, VRChatTotalCacheSize, VRChatCacheSizeLoading } = storeToRefs(useGameStore());
    const { getVRChatCacheSize } = useGameStore();
    const { folderSelectorDialog } = useAdvancedSettingsStore();
    const { isVRChatConfigDialogVisible } = storeToRefs(useAdvancedSettingsStore());
    const modalStore = useModalStore();

    const { t } = useI18n();

    const VRChatConfigFile = ref(/** @type {Record<string, any>} */ ({}));
    // it's a object
    const VRChatConfigList = ref(
        /** @type {Record<string, any>} */ ({
            cache_size: {
                name: t('dialog.config_json.max_cache_size'),
                default: '30',
                type: 'number',
                min: 30
            },
            cache_expiry_delay: {
                name: t('dialog.config_json.cache_expiry_delay'),
                default: '30',
                type: 'number',
                min: 30
            },
            cache_directory: {
                name: t('dialog.config_json.cache_directory'),
                default: '%AppData%\\..\\LocalLow\\VRChat\\VRChat',
                folderBrowser: true
            },
            picture_output_folder: {
                name: t('dialog.config_json.picture_directory'),
                // my pictures folder
                default: `%UserProfile%\\Pictures\\VRChat`,
                folderBrowser: true
            },
            // dynamic_bone_max_affected_transform_count: {
            //     name: 'Dynamic Bones Limit Max Transforms (0 disable all transforms)',
            //     default: '32',
            //     type: 'number',
            //     min: 0
            // },
            // dynamic_bone_max_collider_check_count: {
            //     name: 'Dynamic Bones Limit Max Collider Collisions (0 disable all colliders)',
            //     default: '8',
            //     type: 'number',
            //     min: 0
            // },
            fpv_steadycam_fov: {
                name: t('dialog.config_json.fpv_steadycam_fov'),
                default: '50',
                type: 'number',
                min: 30,
                max: 110
            }
        })
    );

    const loading = ref(false);

    watch(
        () => isVRChatConfigDialogVisible.value,
        async (newValue) => {
            if (newValue) {
                loading.value = true;
                await readVRChatConfigFile();
                loading.value = false;
            }
        }
    );

    const totalCacheSize = computed(() => {
        return VRChatConfigFile.value.cache_size || VRChatTotalCacheSize.value;
    });

    const VRCHAT_RESOLUTION_DEFAULT_KEY = '__default__';

    /**
     *
     * @param row
     */
    function getVRChatResolutionKey(row) {
        const width = Number(row?.width);
        const height = Number(row?.height);
        if (width > 0 && height > 0) {
            return `${width}x${height}`;
        }
        return VRCHAT_RESOLUTION_DEFAULT_KEY;
    }

    const vrchatCameraResolutionKey = computed({
        get: () => {
            const width = Number(VRChatConfigFile.value.camera_res_width);
            const height = Number(VRChatConfigFile.value.camera_res_height);
            if (width > 0 && height > 0) {
                return `${width}x${height}`;
            }
            return VRCHAT_RESOLUTION_DEFAULT_KEY;
        },
        set: (value) => {
            const row = VRChatCameraResolutions.find((r) => getVRChatResolutionKey(r) === value);
            if (row) {
                setVRChatCameraResolution(row);
            }
        }
    });

    const vrchatSpoutResolutionKey = computed({
        get: () => {
            const width = Number(VRChatConfigFile.value.camera_spout_res_width);
            const height = Number(VRChatConfigFile.value.camera_spout_res_height);
            if (width > 0 && height > 0) {
                return `${width}x${height}`;
            }
            return VRCHAT_RESOLUTION_DEFAULT_KEY;
        },
        set: (value) => {
            const row = VRChatScreenshotResolutions.find((r) => getVRChatResolutionKey(r) === value);
            if (row) {
                setVRChatSpoutResolution(row);
            }
        }
    });

    const vrchatScreenshotResolutionKey = computed({
        get: () => {
            const width = Number(VRChatConfigFile.value.screenshot_res_width);
            const height = Number(VRChatConfigFile.value.screenshot_res_height);
            if (width > 0 && height > 0) {
                return `${width}x${height}`;
            }
            return VRCHAT_RESOLUTION_DEFAULT_KEY;
        },
        set: (value) => {
            const row = VRChatScreenshotResolutions.find((r) => getVRChatResolutionKey(r) === value);
            if (row) {
                setVRChatScreenshotResolution(row);
            }
        }
    });

    /**
     *
     */
    function showDeleteAllVRChatCacheConfirm() {
        modalStore
            .confirm({
                description: t('confirm.clear_cache'),
                title: t('confirm.title')
            })
            .then(({ ok }) => {
                if (ok) {
                    deleteAllVRChatCache();
                }
            })
            .catch(() => {});
    }

    /**
     *
     */
    async function deleteAllVRChatCache() {
        try {
            await AssetBundleManager.DeleteAllCache();
            toast.success(t('message.cache.deleted'));
        } catch (error) {
            toast.error(t('message.cache.delete_error', { error: error.message }));
        }
        getVRChatCacheSize();
    }

    /**
     *
     * @param value
     */
    async function openConfigFolderBrowser(value) {
        const oldPath = VRChatConfigFile.value[value];
        const newPath = await folderSelectorDialog(oldPath);
        if (newPath) {
            VRChatConfigFile.value[value] = newPath;
            refreshDialogValues();
        }
    }

    /**
     *
     */
    function refreshDialogValues() {
        loading.value = true;
        loading.value = false;
    }

    /**
     *
     * @param res
     */
    function setVRChatSpoutResolution(res) {
        VRChatConfigFile.value.camera_spout_res_height = res.height;
        VRChatConfigFile.value.camera_spout_res_width = res.width;
        refreshDialogValues();
    }

    /**
     *
     * @param res
     */
    function setVRChatCameraResolution(res) {
        VRChatConfigFile.value.camera_res_height = res.height;
        VRChatConfigFile.value.camera_res_width = res.width;
        refreshDialogValues();
    }

    /**
     *
     * @param res
     */
    function setVRChatScreenshotResolution(res) {
        VRChatConfigFile.value.screenshot_res_height = res.height;
        VRChatConfigFile.value.screenshot_res_width = res.width;
        refreshDialogValues();
    }

    /**
     *
     */
    function getVRChatCameraResolution() {
        if (VRChatConfigFile.value.camera_res_height && VRChatConfigFile.value.camera_res_width) {
            const res = `${VRChatConfigFile.value.camera_res_width}x${VRChatConfigFile.value.camera_res_height}`;
            return getVRChatResolution(res);
        }
        return '1920x1080 (1080p)';
    }

    /**
     *
     */
    function getVRChatSpoutResolution() {
        if (VRChatConfigFile.value.camera_spout_res_height && VRChatConfigFile.value.camera_spout_res_width) {
            const res = `${VRChatConfigFile.value.camera_spout_res_width}x${VRChatConfigFile.value.camera_spout_res_height}`;
            return getVRChatResolution(res);
        }
        return '1920x1080 (1080p)';
    }

    /**
     *
     */
    function getVRChatScreenshotResolution() {
        if (VRChatConfigFile.value.screenshot_res_height && VRChatConfigFile.value.screenshot_res_width) {
            const res = `${VRChatConfigFile.value.screenshot_res_width}x${VRChatConfigFile.value.screenshot_res_height}`;
            return getVRChatResolution(res);
        }
        return '1920x1080 (1080p)';
    }

    /**
     *
     */
    async function saveVRChatConfigFile() {
        for (const item in VRChatConfigFile.value) {
            if (item === 'picture_output_split_by_date') {
                // this one is default true, it's special
                if (VRChatConfigFile.value[item]) {
                    delete VRChatConfigFile.value[item];
                }
            } else if (VRChatConfigFile.value[item] === '') {
                delete VRChatConfigFile.value[item];
            } else if (typeof VRChatConfigFile.value[item] === 'boolean' && VRChatConfigFile.value[item] === false) {
                delete VRChatConfigFile.value[item];
            } else if (typeof VRChatConfigFile.value[item] === 'string') {
                const parsed = parseInt(VRChatConfigFile.value[item], 10);
                if (!Number.isNaN(parsed)) {
                    VRChatConfigFile.value[item] = parsed;
                }
            }
        }
        await WriteVRChatConfigFile();
        closeDialog();
    }

    /**
     *
     */
    async function WriteVRChatConfigFile() {
        const json = JSON.stringify(VRChatConfigFile.value, null, '\t');
        await invoke('app__write_config_file', { json });
    }

    /**
     *
     */
    async function readVRChatConfigFile() {
        const config = await invoke('app__read_config_file_safe');
        if (config) {
            try {
                const parsedConfig = JSON.parse(config);
                VRChatConfigFile.value = { ...VRChatConfigFile.value, ...parsedConfig };
            } catch {
                toast.error(t('message.cache.invalid_config'));
                throw new Error('Invalid JSON in config.json');
            }
        }
        if (typeof VRChatConfigFile.value.picture_output_split_by_date === 'undefined') {
            VRChatConfigFile.value.picture_output_split_by_date = true;
        }
    }

    /**
     *
     */
    function closeDialog() {
        isVRChatConfigDialogVisible.value = false;
    }
</script>

// src/components/hosts/system-dialogs/VRChatConfigDialog.tsx
import {
    ExternalLinkIcon,
    FolderOpenIcon,
    RefreshCwIcon,
    SaveIcon,
    SparklesIcon,
    Trash2Icon
} from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';

import { userFacingErrorMessage } from '@/lib/errorDisplay';
import { cn } from '@/lib/utils';
import { assetBundleRepository } from '@/repositories/assetBundleRepository';
import {
    openExternalLink,
    openFolderSelectorDialog,
    readVrchatConfigFileSafe,
    writeVrchatConfigFile
} from '@/services/shellIntegrationService';
import { links } from '@/shared/constants/link';
import {
    VRChatCameraResolutions,
    VRChatScreenshotResolutions
} from '@/shared/constants/settings';
import { useModalStore } from '@/state/modalStore';
import { Button } from '@/ui/shadcn/button';
import {
    Card,
    CardContent,
    CardFooter,
    CardHeader,
    CardTitle
} from '@/ui/shadcn/card';
import { Checkbox } from '@/ui/shadcn/checkbox';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle
} from '@/ui/shadcn/dialog';
import { Field, FieldGroup, FieldLabel } from '@/ui/shadcn/field';
import { Input } from '@/ui/shadcn/input';
import {
    InputGroup,
    InputGroupAddon,
    InputGroupButton,
    InputGroupInput
} from '@/ui/shadcn/input-group';
import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectTrigger,
    SelectValue
} from '@/ui/shadcn/select';

function getResolutionKey(row: any) {
    const width = Number(row?.width);
    const height = Number(row?.height);
    return width > 0 && height > 0 ? `${width}x${height}` : '__default__';
}

function applyResolution(config: any, keyPrefix: any, value: any) {
    if (value === '__default__') {
        return {
            ...config,
            [`${keyPrefix}_width`]: '',
            [`${keyPrefix}_height`]: ''
        };
    }

    const [width, height] = value.split('x');
    return {
        ...config,
        [`${keyPrefix}_width`]: Number(width) || '',
        [`${keyPrefix}_height`]: Number(height) || ''
    };
}

function normalizeVrchatConfigForSave(config: any) {
    const output: any = { ...config };
    for (const key of Object.keys(output)) {
        if (key === 'picture_output_split_by_date') {
            if (output[key]) {
                delete output[key];
            }
        } else if (output[key] === '' || output[key] === false) {
            delete output[key];
        } else if (typeof output[key] === 'string') {
            const parsed = Number.parseInt(output[key], 10);
            if (!Number.isNaN(parsed)) {
                output[key] = parsed;
            }
        }
    }
    return output;
}

function ResolutionSelect({ label, value, rows, onValueChange }: any) {
    return (
        <Field>
            <FieldLabel>{label}</FieldLabel>
            <Select value={value} onValueChange={onValueChange}>
                <SelectTrigger>
                    <SelectValue />
                </SelectTrigger>
                <SelectContent>
                    <SelectGroup>
                        {rows.map((row: any) => (
                            <SelectItem
                                key={row.name}
                                value={getResolutionKey(row)}
                            >
                                {row.name}
                            </SelectItem>
                        ))}
                    </SelectGroup>
                </SelectContent>
            </Select>
        </Field>
    );
}

export function VRChatConfigDialog({ open, onOpenChange }: any) {
    const { t } = useTranslation();
    const confirm = useModalStore((state: any) => state.confirm);
    const loadRequestRef = useRef(0);
    const [config, setConfig] = useState<any>({
        picture_output_split_by_date: true
    });
    const [cacheSize, setCacheSize] = useState('');
    const [loading, setLoading] = useState(false);

    const configFields = useMemo(
        () => [
            [
                'cache_size',
                t('dialog.config_json.max_cache_size'),
                '30',
                'number'
            ],
            [
                'cache_expiry_delay',
                t('dialog.config_json.cache_expiry_delay'),
                '30',
                'number'
            ],
            [
                'cache_directory',
                t('dialog.config_json.cache_directory'),
                '%AppData%\\..\\LocalLow\\VRChat\\VRChat',
                'text'
            ],
            [
                'picture_output_folder',
                t('dialog.config_json.picture_directory'),
                '%UserProfile%\\Pictures\\VRChat',
                'text'
            ],
            [
                'fpv_steadycam_fov',
                t('dialog.config_json.fpv_steadycam_fov'),
                '50',
                'number'
            ]
        ],
        [t]
    );

    async function loadConfig() {
        const requestId = loadRequestRef.current + 1;
        loadRequestRef.current = requestId;
        setLoading(true);
        try {
            const [configJson, nextCacheSize] = await Promise.all([
                readVrchatConfigFileSafe(),
                assetBundleRepository.getCacheSize().catch(() => 0)
            ]);
            if (requestId !== loadRequestRef.current) {
                return;
            }
            const parsed = configJson ? JSON.parse(configJson) : {};
            setConfig({
                picture_output_split_by_date: true,
                ...parsed
            });
            const cacheBytes = Number(nextCacheSize) || 0;
            setCacheSize(
                cacheBytes > 0
                    ? `${(cacheBytes / 1024 / 1024 / 1024).toFixed(2)} GB`
                    : '0 GB'
            );
        } catch (error) {
            if (requestId !== loadRequestRef.current) {
                return;
            }
            toast.error(
                userFacingErrorMessage(
                    error,
                    t(
                        'host.system_dialogs.toast.failed_to_load_vrchat_configuration'
                    )
                )
            );
        } finally {
            if (requestId === loadRequestRef.current) {
                setLoading(false);
            }
        }
    }

    useEffect(() => {
        if (open) {
            loadConfig();
        } else {
            loadRequestRef.current += 1;
        }
    }, [open]);

    async function openFolderBrowser(key: any) {
        const selected = await openFolderSelectorDialog(
            config[key] || ''
        ).catch((error: any) => {
            toast.error(
                userFacingErrorMessage(
                    error,
                    t('host.system_dialogs.toast.failed_to_select_folder')
                )
            );
            return '';
        });
        if (selected) {
            setConfig((current: any) => ({ ...current, [key]: selected }));
        }
    }

    async function handleSweepCache() {
        setLoading(true);
        try {
            const removed = await assetBundleRepository.sweepCache();
            toast.success(
                Array.isArray(removed)
                    ? t(
                          'host.system_dialogs.toast.removed_value_cache_entries',
                          { value: removed.length }
                      )
                    : t('message.cache.deleted')
            );
            await loadConfig();
        } catch (error) {
            toast.error(
                userFacingErrorMessage(
                    error,
                    t('host.system_dialogs.toast.failed_to_sweep_asset_cache')
                )
            );
        } finally {
            setLoading(false);
        }
    }

    async function handleDeleteAllCache() {
        const result = await confirm({
            title: t('confirm.title'),
            description: t('confirm.clear_cache'),
            confirmText: t('dialog.config_json.delete_cache'),
            cancelText: t('dialog.config_json.cancel'),
            destructive: true
        });
        if (!result.ok) {
            return;
        }
        setLoading(true);
        try {
            await assetBundleRepository.deleteAllCache();
            toast.success(t('message.cache.deleted'));
            await loadConfig();
        } catch (error) {
            toast.error(
                userFacingErrorMessage(
                    error,
                    t('host.system_dialogs.toast.failed_to_delete_asset_cache')
                )
            );
        } finally {
            setLoading(false);
        }
    }

    async function handleSave() {
        setLoading(true);
        try {
            const json = JSON.stringify(
                normalizeVrchatConfigForSave(config),
                null,
                '\t'
            );
            await writeVrchatConfigFile(json);
            toast.success(t('dialog.system.success.saved_vrchat_config'));
            onOpenChange(false);
        } catch (error) {
            toast.error(
                userFacingErrorMessage(
                    error,
                    t(
                        'host.system_dialogs.toast.failed_to_save_vrchat_configuration'
                    )
                )
            );
        } finally {
            setLoading(false);
        }
    }

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="grid max-h-[85vh] w-[calc(100%-2rem)] max-w-5xl grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden sm:max-w-5xl">
                <DialogHeader>
                    <DialogTitle>{t('dialog.config_json.header')}</DialogTitle>
                    <DialogDescription>
                        {t('dialog.config_json.description1')}{' '}
                        {t('dialog.config_json.description2')}
                    </DialogDescription>
                </DialogHeader>
                <div className="grid min-h-0 gap-4 overflow-y-auto pr-1 lg:grid-cols-[minmax(0,1fr)_18rem] lg:overflow-hidden lg:pr-0">
                    <div className="min-h-0 lg:overflow-y-auto lg:pr-1">
                        <FieldGroup>
                            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                                {configFields.map(
                                    ([key, label, placeholder, type]: any) => {
                                        const isPathField =
                                            key.endsWith('_directory') ||
                                            key.endsWith('_folder');

                                        return (
                                            <Field
                                                key={key}
                                                className={cn(
                                                    isPathField &&
                                                        'md:col-span-2 xl:col-span-3'
                                                )}
                                            >
                                                <FieldLabel
                                                    htmlFor={`config-json-${key}`}
                                                >
                                                    {label}
                                                </FieldLabel>
                                                {isPathField ? (
                                                    <InputGroup>
                                                        <InputGroupInput
                                                            id={`config-json-${key}`}
                                                            type={type}
                                                            value={
                                                                config[key] ??
                                                                ''
                                                            }
                                                            placeholder={
                                                                placeholder
                                                            }
                                                            onChange={(
                                                                event: any
                                                            ) =>
                                                                setConfig(
                                                                    (
                                                                        current: any
                                                                    ) => ({
                                                                        ...current,
                                                                        [key]: event
                                                                            .target
                                                                            .value
                                                                    })
                                                                )
                                                            }
                                                        />
                                                        <InputGroupAddon align="inline-end">
                                                            <InputGroupButton
                                                                type="button"
                                                                onClick={() => {
                                                                    openFolderBrowser(
                                                                        key
                                                                    );
                                                                }}
                                                            >
                                                                <FolderOpenIcon data-icon="inline-start" />
                                                                {t(
                                                                    'dialog.screenshot_metadata.browse'
                                                                )}
                                                            </InputGroupButton>
                                                        </InputGroupAddon>
                                                    </InputGroup>
                                                ) : (
                                                    <Input
                                                        id={`config-json-${key}`}
                                                        type={type}
                                                        value={
                                                            config[key] ?? ''
                                                        }
                                                        placeholder={
                                                            placeholder
                                                        }
                                                        onChange={(
                                                            event: any
                                                        ) =>
                                                            setConfig(
                                                                (
                                                                    current: any
                                                                ) => ({
                                                                    ...current,
                                                                    [key]: event
                                                                        .target
                                                                        .value
                                                                })
                                                            )
                                                        }
                                                    />
                                                )}
                                            </Field>
                                        );
                                    }
                                )}
                            </div>

                            <div className="grid gap-4 md:grid-cols-3">
                                <ResolutionSelect
                                    label={t(
                                        'dialog.config_json.camera_resolution'
                                    )}
                                    value={getResolutionKey({
                                        width: config.camera_res_width,
                                        height: config.camera_res_height
                                    })}
                                    rows={VRChatCameraResolutions}
                                    onValueChange={(value: any) =>
                                        setConfig((current: any) =>
                                            applyResolution(
                                                current,
                                                'camera_res',
                                                value
                                            )
                                        )
                                    }
                                />
                                <ResolutionSelect
                                    label={t(
                                        'dialog.config_json.spout_resolution'
                                    )}
                                    value={getResolutionKey({
                                        width: config.camera_spout_res_width,
                                        height: config.camera_spout_res_height
                                    })}
                                    rows={VRChatScreenshotResolutions}
                                    onValueChange={(value: any) =>
                                        setConfig((current: any) =>
                                            applyResolution(
                                                current,
                                                'camera_spout_res',
                                                value
                                            )
                                        )
                                    }
                                />
                                <ResolutionSelect
                                    label={t(
                                        'dialog.config_json.screenshot_resolution'
                                    )}
                                    value={getResolutionKey({
                                        width: config.screenshot_res_width,
                                        height: config.screenshot_res_height
                                    })}
                                    rows={VRChatScreenshotResolutions}
                                    onValueChange={(value: any) =>
                                        setConfig((current: any) =>
                                            applyResolution(
                                                current,
                                                'screenshot_res',
                                                value
                                            )
                                        )
                                    }
                                />
                            </div>

                            <div className="grid gap-3 md:grid-cols-2">
                                <Field orientation="horizontal">
                                    <Checkbox
                                        id="vrchat-config-picture-sort-by-date"
                                        checked={Boolean(
                                            config.picture_output_split_by_date
                                        )}
                                        onCheckedChange={(checked: any) =>
                                            setConfig((current: any) => ({
                                                ...current,
                                                picture_output_split_by_date:
                                                    Boolean(checked)
                                            }))
                                        }
                                    />
                                    <FieldLabel htmlFor="vrchat-config-picture-sort-by-date">
                                        {t(
                                            'dialog.config_json.picture_sort_by_date'
                                        )}
                                    </FieldLabel>
                                </Field>
                                <Field orientation="horizontal">
                                    <Checkbox
                                        id="vrchat-config-disable-rich-presence"
                                        checked={Boolean(
                                            config.disableRichPresence
                                        )}
                                        onCheckedChange={(checked: any) =>
                                            setConfig((current: any) => ({
                                                ...current,
                                                disableRichPresence:
                                                    Boolean(checked)
                                            }))
                                        }
                                    />
                                    <FieldLabel htmlFor="vrchat-config-disable-rich-presence">
                                        {t(
                                            'dialog.config_json.disable_discord_presence'
                                        )}
                                    </FieldLabel>
                                </Field>
                            </div>
                        </FieldGroup>
                    </div>
                    <div className="min-h-0 p-px lg:overflow-y-auto">
                        <Card size="sm">
                            <CardHeader>
                                <CardTitle>
                                    {t('dialog.config_json.cache_size')}
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="flex flex-col gap-3">
                                <div className="bg-muted/30 rounded-lg border p-3">
                                    <div className="font-mono text-lg leading-none">
                                        {cacheSize}
                                    </div>
                                </div>
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    disabled={loading}
                                    className="justify-start"
                                    onClick={() => {
                                        loadConfig();
                                    }}
                                >
                                    <RefreshCwIcon data-icon="inline-start" />
                                    {t('dialog.config_json.refresh')}
                                </Button>
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    disabled={loading}
                                    className="justify-start"
                                    onClick={() => {
                                        handleDeleteAllCache();
                                    }}
                                >
                                    <Trash2Icon data-icon="inline-start" />
                                    {t('dialog.config_json.delete_cache')}
                                </Button>
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    disabled={loading}
                                    className="justify-start"
                                    onClick={() => {
                                        handleSweepCache();
                                    }}
                                >
                                    <SparklesIcon data-icon="inline-start" />
                                    {t('dialog.config_json.sweep_cache')}
                                </Button>
                            </CardContent>
                            <CardFooter className="flex-col items-stretch gap-2">
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    className="justify-start"
                                    onClick={() => {
                                        openExternalLink(
                                            links.vrchatDocsConfigurationFile
                                        );
                                    }}
                                >
                                    <ExternalLinkIcon data-icon="inline-start" />
                                    {t('dialog.config_json.vrchat_docs')}
                                </Button>
                            </CardFooter>
                        </Card>
                    </div>
                </div>
                <DialogFooter>
                    <Button
                        type="button"
                        variant="outline"
                        onClick={() => onOpenChange(false)}
                    >
                        {t('dialog.config_json.cancel')}
                    </Button>
                    <Button
                        type="button"
                        disabled={loading}
                        onClick={() => {
                            handleSave();
                        }}
                    >
                        <SaveIcon data-icon="inline-start" />
                        {t('dialog.config_json.save')}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
